### ISSUE TITLE
AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by jaaouani-glitch** [jacklein/rn-bottom-drawer#37]
Hi, I'm trying to use rn-bottom-drawer, but get error message as the title when I swipe up, the error produces on both platform android and iOS.
```
<BottomDrawer containerHeight={Dimensions.get('window').height / 2} offset={0} startUp={false} roundedEdges={true} shadow={true}>
                    <View style={{ flex: 1 }}>
                            <Text>Hi</Text>
                   </View>
</BottomDrawer>
```
my react native version is: 0.63.2 and latest rn-bottom-drawer.

**Comment by Spark-NF** [comment]
Same here (reproduced on Android, didn't try iOS).
I "solved" it by retrograding `react-native` to `0.62.2`.

_EDIT: after a quick investigation, it's caused by the calls to `this.position.setValue` in `Animator.js` not passing the X value, which is then undefined, causing the error. I created the PR #38 to fix this._

**Comment by jaaouani-glitch** [comment]
Thank you, I follow you're solution amazing.

**Comment by Billwall2020** [comment]
The solution is great and works perfectly, please merge it! 👍
